apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: emqx-operator
  namespace: emqx-operator-system
spec:
  interval: 5m
  chart:
    spec:
      chart: emqx-operator
      # version: "2.2.29"
      version: "2.2.14"
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  values:
    development: true
