apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: experimental-emqx-tls
  namespace: experimental-emqx
spec:
  isCA: false
  commonName: experimental-emqx.alexbechmann.dev
  # dnsNames:
  secretName: experimental-emqx-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    group: cert-manager.io
    # kind: ClusterIssuer
    kind: Issuer
    name: selfsigned-issuer
