apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress
  targetNamespace: nginx-ingress
  storageNamespace: nginx-ingress
  interval: 5m
  install:
    createNamespace: true
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: nginx-ingress
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-oci
        namespace: flux-system
  values:
    controller:
      service:
        loadBalancerIP: 192.168.68.35

    udp:
      9683: "experimental-emqx/experimental-emqx-v2-listeners:5683"
      9684: "experimental-emqx/experimental-emqx-v2-listeners:5684"
